version: "3.8"
services:
  bet-maker:
    container_name: bet-maker
    build:
      context: .
      dockerfile: bet-maker/Dockerfile
    command: uvicorn bet-maker.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8001:8000
    depends_on:
      - db
      - redis
    env_file: .env

  redis:
    container_name: gamblr-redis
    image: redis:6.0
    restart: always
    volumes:
      - gamblr-redis:/data
    expose:
      - "6379"

  line-provider:
    container_name: line-provider
    build: 
      context: .
      dockerfile: line-provider/Dockerfile
    command: uvicorn line-provider.app.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8002:8000
    depends_on:
      - db
      - redis
    env_file: .env

  db:
      container_name: gamblr-db
      image: "postgres:15-alpine"
      volumes:
        - gamblr-db:/var/lib/postgresql/data/
      environment:
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_DB}"
      expose:
        - "5432"
        
volumes:
  gamblr-redis: null
  gamblr-db: null