version: "3.8"
services:
  bet-maker:
    container_name: bet-maker
    build:
      context: ./bet-maker
      dockerfile: Dockerfile
    command: bash start-api.sh
    ports:
      - 8001:8000
    depends_on:
      - db
      - redis
    env_file: .env

  redis:
    container_name: gamblr-redis
    image: redis:6.2
    restart: always
    volumes:
      - gamblr-redis:/data
    expose:
      - "6379"

  line-provider:
    container_name: line-provider
    build:
      context: ./line-provider
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8002:8000
    depends_on:
      - db
      - redis
    env_file: .env

  db:
      container_name: gamblr-db
      image: "postgres:15-alpine"
      volumes:
        - gamblr-db:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=${DATABASE_USER}
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_DB=${DATABASE_DB}
      expose:
        - "5432"

volumes:
  gamblr-redis: null
  gamblr-db: null
